### PR TITLE
[#3573] Put back config iterator for backwards compatibility

### LINKED ISSUE #3573: Membership operations on `node.config` object fail
### Describe the bug
When using membership operators (e.g. `"key" in node.config`) in `0.20.0`, you get an error "hasattr(): attribute name must be string". That is because this uses the `__iter__` method under the hood, which has been removed in https://github.com/dbt-labs/dbt/pull/3364/files#diff-007a86f768b23e1516e6d253d71656b96d46672fc7432dbc81d1d9445c98ca05L204-L231.

### Steps To Reproduce
I created a reproduction case in the testing suite here -> https://github.com/dbt-labs/dbt/compare/dbt-labs:f460d27...dbt-labs:8612ce4. 

### Expected behavior
This is a breaking change for folks who are doing these types of operations in their projects, I think it is worth maintaining consistency (https://getdbt.slack.com/archives/CBSQTAPLG/p1626195482486800)

### PR DESCRIPTION
**Pull request by gshank**
resolves #3573

### Description

Put back iterator function in model config to support 'key' in node.config.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: test/integration/043_custom_aliases_test/macros-configs/macros.sql [hunk 1]
```diff
@@ -4,7 +4,7 @@
     {%- if custom_alias_name is none -%}
         {{ node.name }}
     {%- else -%}
-        custom_{{ node.config['alias'] | trim }}
+        custom_{{ node.config['alias'] if 'alias' in node.config else '' | trim }}
```
Comment (kwigley) [inline test/integration/043_custom_aliases_test/macros-configs/macros.sql:7]: 👍

**Review by kwigley — APPROVED** [review]
