### PR TITLE
#3694 

### LINKED ISSUE #3694: dataset not a valid synonym for schema for snapshots when using bigquery
### Describe the bug

```
Running with dbt=0.20.0
Encountered an error:
Compilation Error in snapshot orders_snapshot (snapshots/orders.sql)
  at path []: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.
```  

### Steps To Reproduce

Follow the jaffle_shop tutorial for snapshots. I moved/added models/macros.
With config as per tutorial, run command: ```dbt snapshot ```
Success. Change the config as below, replacing:
target_database >> target_project and 
target_schema >> target_dataset

``` jinja
{% snapshot orders_snapshot %}

{{
    config(
      target_project='daniel-bartley-sandbox',
      target_dataset='dbt_shop', # target_dataset is not a valid alternate syntax to target_schema
      unique_key='customer_payment_id',

      strategy='timestamp',
      updated_at='created_at',
    )
}}

select * from {{ ref('customer_payments__base_js') }}

{% endsnapshot %}
```

run command: ```dbt snapshot```

### Expected behavior

In all other places I've tried project is an accepted synonym for database and dataset is an accepted synonym for schema.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] bigquery

**The output of `dbt --version`:**
``` bash
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.20.0
```

**The operating system you're using:**
```
dbt debug
Running with dbt=0.20.0
dbt version: 0.20.0
python version: 3.9.6
python path: /Users/daniel/git/dbrtly/dbt_shop/.venv/bin/python3.9
os info: macOS-11.5.1-x86_64-i386-64bit
Using profiles.yml file at /Users/daniel/.dbt/profiles.yml
Using dbt_project.yml file at /Users/daniel/git/dbrtly/dbt_shop/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  method: oauth
  database: daniel-bartley-sandbox
  schema: dbt_shop
  location: US
  priority: interactive
  timeout_seconds: 300
  maximum_bytes_billed: None
  Connection test: OK connection ok
```
**The output of `python --version`:**

### Additional context
2021-08-05 11:53:46.642043 (MainThread): Running with dbt=0.20.0
2021-08-05 11:53:47.086201 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=False, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=False, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/Users/daniel/.dbt', profile=None, target=None, vars='{}', log_cache_events=False, use_cache=True, threads=None, models=None, exclude=None, selector_name=None, state=None, defer=None, cls=<class 'dbt.task.snapshot.SnapshotTask'>, which='snapshot', rpc_method='snapshot')
2021-08-05 11:53:47.088382 (MainThread): Tracking: tracking
2021-08-05 11:53:47.100443 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a8d2370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a8d3670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a8d3d60>]}
2021-08-05 11:53:47.143426 (MainThread): Partial parsing not enabled
2021-08-05 11:53:47.241619 (MainThread): Parsing macros/metric_approx_distinct_count.sql
2021-08-05 11:53:47.243615 (MainThread): Parsing macros/metric_sum.sql
2021-08-05 11:53:47.245014 (MainThread): Parsing macros/metric_count.sql
2021-08-05 11:53:47.245977 (MainThread): Parsing macros/metric_max.sql
2021-08-05 11:53:47.247367 (MainThread): Parsing macros/metric_count_distinct.sql
2021-08-05 11:53:47.249377 (MainThread): Parsing macros/metric_avg.sql
2021-08-05 11:53:47.250928 (MainThread): Parsing macros/metric_min.sql
2021-08-05 11:53:47.252402 (MainThread): Parsing macros/anonymise/extract_email_domain.sql
2021-08-05 11:53:47.252813 (MainThread): Parsing macros/generate/generate_enrich_model.sql
2021-08-05 11:53:47.255728 (MainThread): Parsing macros/etc.sql
2021-08-05 11:53:47.257503 (MainThread): Parsing macros/catalog.sql
2021-08-05 11:53:47.263714 (MainThread): Parsing macros/adapters.sql
2021-08-05 11:53:47.281539 (MainThread): Parsing macros/materializations/seed.sql
2021-08-05 11:53:47.283959 (MainThread): Parsing macros/materializations/view.sql
2021-08-05 11:53:47.286404 (MainThread): Parsing macros/materializations/table.sql
2021-08-05 11:53:47.295328 (MainThread): Parsing macros/materializations/copy.sql
2021-08-05 11:53:47.299306 (MainThread): Parsing macros/materializations/incremental.sql
2021-08-05 11:53:47.310457 (MainThread): Parsing macros/materializations/snapshot.sql
2021-08-05 11:53:47.312005 (MainThread): Parsing macros/core.sql
2021-08-05 11:53:47.315330 (MainThread): Parsing macros/materializations/test.sql
2021-08-05 11:53:47.321461 (MainThread): Parsing macros/materializations/helpers.sql
2021-08-05 11:53:47.330721 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-08-05 11:53:47.332226 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-08-05 11:53:47.348391 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-08-05 11:53:47.380495 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-08-05 11:53:47.400194 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-08-05 11:53:47.401748 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-08-05 11:53:47.408685 (MainThread): Parsing macros/materializations/common/merge.sql
2021-08-05 11:53:47.421859 (MainThread): Parsing macros/materializations/table/table.sql
2021-08-05 11:53:47.428241 (MainThread): Parsing macros/materializations/view/view.sql
2021-08-05 11:53:47.433902 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-08-05 11:53:47.438201 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-08-05 11:53:47.438951 (MainThread): Parsing macros/etc/query.sql
2021-08-05 11:53:47.439782 (MainThread): Parsing macros/etc/is_incremental.sql
2021-08-05 11:53:47.441126 (MainThread): Parsing macros/etc/datetime.sql
2021-08-05 11:53:47.449213 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-08-05 11:53:47.451019 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-08-05 11:53:47.452496 (MainThread): Parsing macros/adapters/common.sql
2021-08-05 11:53:47.498333 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-08-05 11:53:47.518104 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-08-05 11:53:47.519888 (MainThread): Parsing macros/schema_tests/unique.sql
2021-08-05 11:53:47.521814 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-08-05 11:53:47.524829 (MainThread): Parsing macros/cross_db_utils/except.sql
2021-08-05 11:53:47.526268 (MainThread): Parsing macros/cross_db_utils/replace.sql
2021-08-05 11:53:47.527595 (MainThread): Parsing macros/cross_db_utils/concat.sql
2021-08-05 11:53:47.528622 (MainThread): Parsing macros/cross_db_utils/datatypes.sql
2021-08-05 11:53:47.534663 (MainThread): Parsing macros/cross_db_utils/_is_relation.sql
2021-08-05 11:53:47.535702 (MainThread): Parsing macros/cross_db_utils/length.sql
2021-08-05 11:53:47.536908 (MainThread): Parsing macros/cross_db_utils/dateadd.sql
2021-08-05 11:53:47.539594 (MainThread): Parsing macros/cross_db_utils/intersect.sql
2021-08-05 11:53:47.540504 (MainThread): Parsing macros/cross_db_utils/right.sql
2021-08-05 11:53:47.542651 (MainThread): Parsing macros/cross_db_utils/datediff.sql
2021-08-05 11:53:47.551953 (MainThread): Parsing macros/cross_db_utils/safe_cast.sql
2021-08-05 11:53:47.553586 (MainThread): Parsing macros/cross_db_utils/hash.sql
2021-08-05 11:53:47.554812 (MainThread): Parsing macros/cross_db_utils/cast_bool_to_text.sql
2021-08-05 11:53:47.556071 (MainThread): Parsing macros/cross_db_utils/identifier.sql
2021-08-05 11:53:47.557531 (MainThread): Parsing macros/cross_db_utils/position.sql
2021-08-05 11:53:47.559030 (MainThread): Parsing macros/cross_db_utils/literal.sql
2021-08-05 11:53:47.559844 (MainThread): Parsing macros/cross_db_utils/current_timestamp.sql
2021-08-05 11:53:47.562895 (MainThread): Parsing macros/cross_db_utils/width_bucket.sql
2021-08-05 11:53:47.567728 (MainThread): Parsing macros/cross_db_utils/last_day.sql
2021-08-05 11:53:47.570970 (MainThread): Parsing macros/cross_db_utils/split_part.sql
2021-08-05 11:53:47.572565 (MainThread): Parsing macros/cross_db_utils/date_trunc.sql
2021-08-05 11:53:47.573852 (MainThread): Parsing macros/cross_db_utils/_is_ephemeral.sql
2021-08-05 11:53:47.575532 (MainThread): Parsing macros/materializations/insert_by_period_materialization.sql
2021-08-05 11:53:47.599287 (MainThread): Parsing macros/web/get_url_host.sql
2021-08-05 11:53:47.600997 (MainThread): Parsing macros/web/get_url_path.sql
2021-08-05 11:53:47.603286 (MainThread): Parsing macros/web/get_url_parameter.sql
2021-08-05 11:53:47.604660 (MainThread): Parsing macros/jinja_helpers/pretty_log_format.sql
2021-08-05 11:53:47.605612 (MainThread): Parsing macros/jinja_helpers/pretty_time.sql
2021-08-05 11:53:47.606650 (MainThread): Parsing macros/jinja_helpers/log_info.sql
2021-08-05 11:53:47.607706 (MainThread): Parsing macros/jinja_helpers/slugify.sql
2021-08-05 11:53:47.608726 (MainThread): Parsing macros/schema_tests/fewer_rows_than.sql
2021-08-05 11:53:47.610232 (MainThread): Parsing macros/schema_tests/equal_rowcount.sql
2021-08-05 11:53:47.611661 (MainThread): Parsing macros/schema_tests/relationships_where.sql
2021-08-05 11:53:47.613704 (MainThread): Parsing macros/schema_tests/recency.sql
2021-08-05 11:53:47.615245 (MainThread): Parsing macros/schema_tests/not_constant.sql
2021-08-05 11:53:47.616315 (MainThread): Parsing macros/schema_tests/accepted_range.sql
2021-08-05 11:53:47.618574 (MainThread): Parsing macros/schema_tests/not_accepted_values.sql
2021-08-05 11:53:47.620454 (MainThread): Parsing macros/schema_tests/test_unique_where.sql
2021-08-05 11:53:47.621688 (MainThread): Parsing macros/schema_tests/at_least_one.sql
2021-08-05 11:53:47.622769 (MainThread): Parsing macros/schema_tests/unique_combination_of_columns.sql
2021-08-05 11:53:47.625269 (MainThread): Parsing macros/schema_tests/cardinality_equality.sql
2021-08-05 11:53:47.627041 (MainThread): Parsing macros/schema_tests/expression_is_true.sql
2021-08-05 11:53:47.628610 (MainThread): Parsing macros/schema_tests/sequential_values.sql
2021-08-05 11:53:47.631063 (MainThread): Parsing macros/schema_tests/test_not_null_where.sql
2021-08-05 11:53:47.632299 (MainThread): Parsing macros/schema_tests/equality.sql
2021-08-05 11:53:47.635396 (MainThread): Parsing macros/schema_tests/mutually_exclusive_ranges.sql
2021-08-05 11:53:47.643869 (MainThread): Parsing macros/sql/date_spine.sql
2021-08-05 11:53:47.648131 (MainThread): Parsing macros/sql/nullcheck_table.sql
2021-08-05 11:53:47.649535 (MainThread): Parsing macros/sql/get_relations_by_pattern.sql
2021-08-05 11:53:47.652747 (MainThread): Parsing macros/sql/generate_series.sql
2021-08-05 11:53:47.656719 (MainThread): Parsing macros/sql/get_relations_by_prefix.sql
2021-08-05 11:53:47.659769 (MainThread): Parsing macros/sql/get_tables_by_prefix_sql.sql
2021-08-05 11:53:47.661220 (MainThread): Parsing macros/sql/star.sql
2021-08-05 11:53:47.664182 (MainThread): Parsing macros/sql/unpivot.sql
2021-08-05 11:53:47.671518 (MainThread): Parsing macros/sql/union.sql
2021-08-05 11:53:47.678964 (MainThread): Parsing macros/sql/groupby.sql
2021-08-05 11:53:47.680119 (MainThread): Parsing macros/sql/surrogate_key.sql
2021-08-05 11:53:47.683166 (MainThread): Parsing macros/sql/safe_add.sql
2021-08-05 11:53:47.684581 (MainThread): Parsing macros/sql/nullcheck.sql
2021-08-05 11:53:47.686019 (MainThread): Parsing macros/sql/get_tables_by_pattern_sql.sql
2021-08-05 11:53:47.691924 (MainThread): Parsing macros/sql/get_column_values.sql
2021-08-05 11:53:47.696335 (MainThread): Parsing macros/sql/pivot.sql
2021-08-05 11:53:47.700024 (MainThread): Parsing macros/sql/get_query_results_as_dict.sql
2021-08-05 11:53:47.702140 (MainThread): Parsing macros/sql/haversine_distance.sql
2021-08-05 11:53:47.707773 (MainThread): Parsing macros/generate_model_yaml.sql
2021-08-05 11:53:47.711117 (MainThread): Parsing macros/generate_source_yaml.sql
2021-08-05 11:53:47.717583 (MainThread): Parsing macros/generate_base_model.sql
2021-08-05 11:53:47.720387 (MainThread): Parsing macros/get_date_dimension.sql
2021-08-05 11:53:47.743308 (MainThread): Parsing macros/get_base_dates.sql
2021-08-05 11:53:47.747994 (MainThread): Parsing macros/fiscal_date/get_fiscal_year_dates.sql
2021-08-05 11:53:47.751932 (MainThread): Parsing macros/fiscal_date/get_fiscal_periods.sql
2021-08-05 11:53:47.753808 (MainThread): Parsing macros/calendar_date/tomorrow.sql
2021-08-05 11:53:47.754329 (MainThread): Parsing macros/calendar_date/next_week.sql
2021-08-05 11:53:47.754811 (MainThread): Parsing macros/calendar_date/next_month_name.sql
2021-08-05 11:53:47.755397 (MainThread): Parsing macros/calendar_date/next_month.sql
2021-08-05 11:53:47.755850 (MainThread): Parsing macros/calendar_date/day_name.sql
2021-08-05 11:53:47.758694 (MainThread): Parsing macros/calendar_date/to_unixtimestamp.sql
2021-08-05 11:53:47.760177 (MainThread): Parsing macros/calendar_date/n_days_away.sql
2021-08-05 11:53:47.760855 (MainThread): Parsing macros/calendar_date/week_start.sql
2021-08-05 11:53:47.764011 (MainThread): Parsing macros/calendar_date/iso_week_start.sql
2021-08-05 11:53:47.766640 (MainThread): Parsing macros/calendar_date/n_days_ago.sql
2021-08-05 11:53:47.767677 (MainThread): Parsing macros/calendar_date/last_week.sql
2021-08-05 11:53:47.768137 (MainThread): Parsing macros/calendar_date/now.sql
2021-08-05 11:53:47.768714 (MainThread): Parsing macros/calendar_date/periods_since.sql
2021-08-05 11:53:47.769321 (MainThread): Parsing macros/calendar_date/today.sql
2021-08-05 11:53:47.769765 (MainThread): Parsing macros/calendar_date/last_month.sql
2021-08-05 11:53:47.770209 (MainThread): Parsing macros/calendar_date/day_of_year.sql
2021-08-05 11:53:47.771844 (MainThread): Parsing macros/calendar_date/last_month_start_date.sql
2021-08-05 11:53:47.772300 (MainThread): Parsing macros/calendar_date/from_unixtimestamp.sql
2021-08-05 11:53:47.778130 (MainThread): Parsing macros/calendar_date/n_months_ago.sql
2021-08-05 11:53:47.779013 (MainThread): Parsing macros/calendar_date/date_part.sql
2021-08-05 11:53:47.780253 (MainThread): Parsing macros/calendar_date/n_weeks_away.sql
2021-08-05 11:53:47.781048 (MainThread): Parsing macros/calendar_date/day_of_month.sql
2021-08-05 11:53:47.781957 (MainThread): Parsing macros/calendar_date/yesterday.sql
2021-08-05 11:53:47.782517 (MainThread): Parsing macros/calendar_date/day_of_week.sql
2021-08-05 11:53:47.789991 (MainThread): Parsing macros/calendar_date/iso_week_end.sql
2021-08-05 11:53:47.792254 (MainThread): Parsing macros/calendar_date/next_month_start_date.sql
2021-08-05 11:53:47.792746 (MainThread): Parsing macros/calendar_date/n_weeks_ago.sql
2021-08-05 11:53:47.793808 (MainThread): Parsing macros/calendar_date/month_name.sql
2021-08-05 11:53:47.796468 (MainThread): Parsing macros/calendar_date/last_month_name.sql
2021-08-05 11:53:47.797072 (MainThread): Parsing macros/calendar_date/week_of_year.sql
2021-08-05 11:53:47.798660 (MainThread): Parsing macros/calendar_date/convert_timezone.sql
2021-08-05 11:53:47.802714 (MainThread): Parsing macros/calendar_date/n_months_away.sql
2021-08-05 11:53:47.803969 (MainThread): Parsing macros/calendar_date/next_week_start_date.sql
2021-08-05 11:53:47.804713 (MainThread): Parsing macros/calendar_date/this_week.sql
2021-08-05 11:53:47.805308 (MainThread): Parsing macros/calendar_date/iso_week_of_year.sql
2021-08-05 11:53:47.809745 (MainThread): Parsing macros/calendar_date/week_end.sql
2021-08-05 11:53:47.812228 (MainThread): Parsing macros/calendar_date/next_month_number.sql
2021-08-05 11:53:47.812861 (MainThread): Parsing macros/calendar_date/last_month_number.sql
2021-08-05 11:53:47.813462 (MainThread): Parsing macros/utils/datatypes.sql
2021-08-05 11:53:47.814838 (MainThread): Parsing macros/regex/regexp_instr.sql
2021-08-05 11:53:47.817047 (MainThread): Parsing macros/math/log_natural.sql
2021-08-05 11:53:47.818586 (MainThread): Parsing macros/math/rand.sql
2021-08-05 11:53:47.820140 (MainThread): Parsing macros/math/median.sql
2021-08-05 11:53:47.820632 (MainThread): Parsing macros/math/percentile_cont.sql
2021-08-05 11:53:47.822488 (MainThread): Parsing macros/schema_tests/_generalized/expression_between.sql
2021-08-05 11:53:47.826459 (MainThread): Parsing macros/schema_tests/_generalized/expression_is_true.sql
2021-08-05 11:53:47.830751 (MainThread): Parsing macros/schema_tests/_generalized/equal_expression.sql
2021-08-05 11:53:47.846871 (MainThread): Parsing macros/schema_tests/_generalized/_truth_expression.sql
2021-08-05 11:53:47.847872 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_like_pattern.sql
2021-08-05 11:53:47.849142 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_like_pattern_list.sql
2021-08-05 11:53:47.851749 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_regex.sql
2021-08-05 11:53:47.853140 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_value_lengths_to_equal.sql
2021-08-05 11:53:47.854379 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_value_lengths_to_be_between.sql
2021-08-05 11:53:47.856066 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_regex.sql
2021-08-05 11:53:47.857350 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_regex_list.sql
2021-08-05 11:53:47.859548 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_regex_list.sql
2021-08-05 11:53:47.861926 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_like_pattern_list.sql
2021-08-05 11:53:47.864330 (MainThread): Parsing macros/schema_tests/string_matching/_get_like_pattern_expression.sql
2021-08-05 11:53:47.865004 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_like_pattern.sql
2021-08-05 11:53:47.866198 (MainThread): Parsing macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql
2021-08-05 11:53:47.867427 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_columns_to_contain_set.sql
2021-08-05 11:53:47.869117 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table.sql
2021-08-05 11:53:47.870268 (MainThread): Parsing macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
2021-08-05 11:53:47.872663 (MainThread): Parsing macros/schema_tests/table_shape/expect_column_to_exist.sql
2021-08-05 11:53:47.875065 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_equal.sql
2021-08-05 11:53:47.877865 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_be_between.sql
2021-08-05 11:53:47.879413 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table_times_factor.sql
2021-08-05 11:53:47.880331 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql
2021-08-05 11:53:47.881796 (MainThread): Parsing macros/schema_tests/table_shape/_get_column_list.sql
2021-08-05 11:53:47.882742 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql
2021-08-05 11:53:47.884380 (MainThread): Parsing macros/schema_tests/table_shape/_list_intersect.sql
2021-08-05 11:53:47.885563 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_column_count_to_equal_other_table.sql
2021-08-05 11:53:47.886770 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_column_count_to_equal.sql
2021-08-05 11:53:47.887681 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_column_count_to_be_between.sql
2021-08-05 11:53:47.889869 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_not_be_in_set.sql
2021-08-05 11:53:47.891663 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql
2021-08-05 11:53:47.893704 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql
2021-08-05 11:53:47.895345 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_null.sql
2021-08-05 11:53:47.896369 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_unique.sql
2021-08-05 11:53:47.897015 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_between.sql
2021-08-05 11:53:47.898635 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql
2021-08-05 11:53:47.900390 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql
2021-08-05 11:53:47.903727 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_of_type.sql
2021-08-05 11:53:47.904404 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_not_be_null.sql
2021-08-05 11:53:47.905424 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_min_to_be_between.sql
2021-08-05 11:53:47.907069 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_unique_value_count_to_be_between.sql
2021-08-05 11:53:47.908731 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_quantile_values_to_be_between.sql
2021-08-05 11:53:47.910659 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_median_to_be_between.sql
2021-08-05 11:53:47.912439 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_proportion_of_unique_values_to_be_between.sql
2021-08-05 11:53:47.914213 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_equal_set.sql
2021-08-05 11:53:47.916100 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_most_common_value_to_be_in_set.sql
2021-08-05 11:53:47.921341 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_contain_set.sql
2021-08-05 11:53:47.923287 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal.sql
2021-08-05 11:53:47.924732 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_sum_to_be_between.sql
2021-08-05 11:53:47.926496 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_stdev_to_be_between.sql
2021-08-05 11:53:47.930100 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_mean_to_be_between.sql
2021-08-05 11:53:47.931781 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_max_to_be_between.sql
2021-08-05 11:53:47.933474 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_be_greater_than.sql
2021-08-05 11:53:47.935082 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql
2021-08-05 11:53:47.937276 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal_other_table.sql
2021-08-05 11:53:47.938991 (MainThread): Parsing macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql
2021-08-05 11:53:47.945334 (MainThread): Parsing macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql
2021-08-05 11:53:47.955449 (MainThread): Parsing macros/schema_tests/distributional/expect_column_values_to_be_within_n_stdevs.sql
2021-08-05 11:53:47.958469 (MainThread): Parsing macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql
2021-08-05 11:53:47.964779 (MainThread): Parsing macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql
2021-08-05 11:53:47.969631 (MainThread): Parsing macros/schema_tests/multi-column/expect_multicolumn_sum_to_equal.sql
2021-08-05 11:53:47.971566 (MainThread): Parsing macros/schema_tests/multi-column/expect_column_pair_values_to_be_equal.sql
2021-08-05 11:53:47.972829 (MainThread): Parsing macros/schema_tests/multi-column/expect_column_pair_values_A_to_be_greater_than_B.sql
2021-08-05 11:53:47.974235 (MainThread): Parsing macros/schema_tests/multi-column/expect_column_pair_values_to_be_in_set.sql
2021-08-05 11:53:48.441987 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders".
2021-08-05 11:53:48.495188 (MainThread): Acquiring new bigquery connection "model.dbt_shop.iowa_liquor_sales".
2021-08-05 11:53:48.500073 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer_payments__base_js".
2021-08-05 11:53:48.504959 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__base_js".
2021-08-05 11:53:48.509842 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__base_js".
2021-08-05 11:53:48.514523 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__base_abc".
2021-08-05 11:53:48.519082 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer_payments__base_abc".
2021-08-05 11:53:48.524892 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__base_abc".
2021-08-05 11:53:48.529921 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__agg".
2021-08-05 11:53:48.544496 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__enrich".
2021-08-05 11:53:48.562075 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__enrich".
2021-08-05 11:53:48.566085 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__blend".
2021-08-05 11:53:48.571399 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__blend".
2021-08-05 11:53:48.576786 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer_payments__blend".
2021-08-05 11:53:48.591740 (MainThread): Acquiring new bigquery connection "snapshot.dbt_shop.orders_snapshot".
2021-08-05 11:53:48.612956 (MainThread): Acquiring new bigquery connection "test.dbt_shop.assert_total_payment_amount_is_positive.sql".
2021-08-05 11:53:48.616389 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.629739 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.631454 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.632980 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.695802 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.697576 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.699177 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.710692 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.712401 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.714228 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.762238 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.763926 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.769989 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.771906 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.774024 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.775780 (MainThread): 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
2021-08-05 11:53:48.853323 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '128fb603-3beb-4f0b-8fee-1cbd9d68c3f6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a8d2160>]}
2021-08-05 11:53:48.871220 (MainThread): write_gpickle is deprecated and will be removed in 3.0.Use ``pickle.dump(G, path, protocol)``
2021-08-05 11:53:48.872053 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '128fb603-3beb-4f0b-8fee-1cbd9d68c3f6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a8b8250>]}
2021-08-05 11:53:48.872294 (MainThread): Found 14 models, 13 tests, 1 snapshot, 0 analyses, 575 macros, 0 operations, 3 seed files, 4 sources, 0 exposures
2021-08-05 11:53:48.874835 (MainThread): 
2021-08-05 11:53:48.875231 (MainThread): Acquiring new bigquery connection "master".
2021-08-05 11:53:48.876035 (ThreadPoolExecutor-0_0): Acquiring new bigquery connection "list_daniel-bartley-sandbox".
2021-08-05 11:53:48.876227 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-08-05 11:53:50.692647 (ThreadPoolExecutor-1_0): Acquiring new bigquery connection "list_daniel-bartley-sandbox_dbt_shop".
2021-08-05 11:53:50.693312 (ThreadPoolExecutor-1_1): Acquiring new bigquery connection "list_daniel-bartley-sandbox_dbt_shop_seeds".
2021-08-05 11:53:50.693454 (ThreadPoolExecutor-1_0): Opening a new connection, currently in state closed
2021-08-05 11:53:50.693811 (ThreadPoolExecutor-1_2): Acquiring new bigquery connection "list_daniel-bartley-sandbox_dbt_shop_dbt_test__audit".
2021-08-05 11:53:50.694030 (ThreadPoolExecutor-1_1): Opening a new connection, currently in state init
2021-08-05 11:53:50.694256 (ThreadPoolExecutor-1_0): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:50.694382 (ThreadPoolExecutor-1_2): Opening a new connection, currently in state init
2021-08-05 11:53:50.694516 (ThreadPoolExecutor-1_1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:50.695321 (ThreadPoolExecutor-1_2): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:51.403238 (MainThread): 21:53:51 | Concurrency: 4 threads (target='dev')
2021-08-05 11:53:51.403564 (MainThread): 21:53:51 | 
2021-08-05 11:53:51.407555 (Thread-1): Began running node snapshot.dbt_shop.orders_snapshot
2021-08-05 11:53:51.407954 (Thread-1): 21:53:51 | 1 of 1 START snapshot dbt_shop.orders_snapshot....................... [RUN]
2021-08-05 11:53:51.408414 (Thread-1): Acquiring new bigquery connection "snapshot.dbt_shop.orders_snapshot".
2021-08-05 11:53:51.408580 (Thread-1): Compiling snapshot.dbt_shop.orders_snapshot
2021-08-05 11:53:51.414652 (Thread-1): finished collecting timing info
2021-08-05 11:53:51.439832 (Thread-1): Opening a new connection, currently in state closed
2021-08-05 11:53:51.440186 (Thread-1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:52.070976 (Thread-1): unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.105.151', 59472), raddr=('142.250.71.74', 443)>
2021-08-05 11:53:52.071160 (Thread-1): unclosed <ssl.SSLSocket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.105.151', 59474), raddr=('172.217.167.106', 443)>
2021-08-05 11:53:52.071301 (Thread-1): unclosed <ssl.SSLSocket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.105.151', 59477), raddr=('172.217.167.106', 443)>
2021-08-05 11:53:52.079961 (Thread-1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:52.805364 (Thread-1): On snapshot.dbt_shop.orders_snapshot: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "dbt_shop", "target_name": "dev", "node_id": "snapshot.dbt_shop.orders_snapshot"} */

        

  create or replace table `daniel-bartley-sandbox`.`dbt_shop`.`orders_snapshot__dbt_tmp`
  
  
  OPTIONS(
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 hour)
    )
  as (
    with snapshot_query as (

        

select * from `daniel-bartley-sandbox`.`dbt_shop`.`customer_payments__base_js`

    ),

    snapshotted_data as (

        select *,
            customer_payment_id as dbt_unique_key

        from `daniel-bartley-sandbox`.`dbt_shop`.`orders_snapshot`
        where dbt_valid_to is null

    ),

    insertions_source_data as (

        select
            *,
            customer_payment_id as dbt_unique_key,
            created_at as dbt_updated_at,
            created_at as dbt_valid_from,
            nullif(created_at, created_at) as dbt_valid_to,
            to_hex(md5(concat(coalesce(cast(customer_payment_id as string), ''), '|',coalesce(cast(created_at as string), '')))) as dbt_scd_id

        from snapshot_query
    ),

    updates_source_data as (

        select
            *,
            customer_payment_id as dbt_unique_key,
            created_at as dbt_updated_at,
            created_at as dbt_valid_from,
            created_at as dbt_valid_to

        from snapshot_query
    ),

    insertions as (

        select
            'insert' as dbt_change_type,
            source_data.*

        from insertions_source_data as source_data
        left outer join snapshotted_data on snapshotted_data.dbt_unique_key = source_data.dbt_unique_key
        where snapshotted_data.dbt_unique_key is null
           or (
                snapshotted_data.dbt_unique_key is not null
            and (
                (snapshotted_data.dbt_valid_from < source_data.created_at)
            )
        )

    ),

    updates as (

        select
            'update' as dbt_change_type,
            source_data.*,
            snapshotted_data.dbt_scd_id

        from updates_source_data as source_data
        join snapshotted_data on snapshotted_data.dbt_unique_key = source_data.dbt_unique_key
        where (
            (snapshotted_data.dbt_valid_from < source_data.created_at)
        )
    )

    select * from insertions
    union all
    select * from updates
  );
    
2021-08-05 11:53:56.763174 (Thread-1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:57.248557 (Thread-1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:57.909657 (Thread-1): Adding columns ([]) to table `daniel-bartley-sandbox`.`dbt_shop`.`orders_snapshot`".
2021-08-05 11:53:57.909890 (Thread-1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:59.301559 (Thread-1): Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
2021-08-05 11:53:59.715680 (Thread-1): Writing runtime SQL for node "snapshot.dbt_shop.orders_snapshot"
2021-08-05 11:53:59.716243 (Thread-1): On snapshot.dbt_shop.orders_snapshot: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "dbt_shop", "target_name": "dev", "node_id": "snapshot.dbt_shop.orders_snapshot"} */

      merge into `daniel-bartley-sandbox`.`dbt_shop`.`orders_snapshot` as DBT_INTERNAL_DEST
    using `daniel-bartley-sandbox`.`dbt_shop`.`orders_snapshot__dbt_tmp` as DBT_INTERNAL_SOURCE
    on DBT_INTERNAL_SOURCE.dbt_scd_id = DBT_INTERNAL_DEST.dbt_scd_id

    when matched
     and DBT_INTERNAL_DEST.dbt_valid_to is null
     and DBT_INTERNAL_SOURCE.dbt_change_type in ('update', 'delete')
        then update
        set dbt_valid_to = DBT_INTERNAL_SOURCE.dbt_valid_to

    when not matched
     and DBT_INTERNAL_SOURCE.dbt_change_type = 'insert'
        then insert (`customer_payment_id`, `sales_order_id`, `payment_method`, `payment_status`, `payment_amount`, `created_at`, `_batched_at`, `dbt_updated_at`, `dbt_valid_from`, `dbt_valid_to`, `dbt_scd_id`)
        values (`customer_payment_id`, `sales_order_id`, `payment_method`, `payment_status`, `payment_amount`, `created_at`, `_batched_at`, `dbt_updated_at`, `dbt_valid_from`, `dbt_valid_to`, `dbt_scd_id`)
    ;

  
2021-08-05 11:54:02.892644 (Thread-1): On snapshot.dbt_shop.orders_snapshot: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "dbt_shop", "target_name": "dev", "node_id": "snapshot.dbt_shop.orders_snapshot"} */
drop table if exists `daniel-bartley-sandbox`.`dbt_shop`.`orders_snapshot__dbt_tmp`
2021-08-05 11:54:04.853901 (Thread-1): finished collecting timing info
2021-08-05 11:54:04.854511 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '128fb603-3beb-4f0b-8fee-1cbd9d68c3f6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a7c8520>]}
2021-08-05 11:54:04.855009 (Thread-1): 21:54:04 | 1 of 1 OK snapshotted dbt_shop.orders_snapshot....................... [MERGE (0.0 rows, 13.1 KB processed) in 13.45s]
2021-08-05 11:54:04.855185 (Thread-1): Finished running node snapshot.dbt_shop.orders_snapshot
2021-08-05 11:54:04.856807 (MainThread): Acquiring new bigquery connection "master".
2021-08-05 11:54:04.857217 (MainThread): 21:54:04 | 
2021-08-05 11:54:04.857379 (MainThread): 21:54:04 | Finished running 1 snapshot in 15.98s.
2021-08-05 11:54:04.857511 (MainThread): Connection 'master' was properly closed.
2021-08-05 11:54:04.857645 (MainThread): Connection 'snapshot.dbt_shop.orders_snapshot' was properly closed.
2021-08-05 11:54:04.857744 (MainThread): Connection 'list_daniel-bartley-sandbox_dbt_shop_seeds' was properly closed.
2021-08-05 11:54:04.857843 (MainThread): Connection 'list_daniel-bartley-sandbox_dbt_shop_dbt_test__audit' was properly closed.
2021-08-05 11:54:04.875870 (MainThread): 
2021-08-05 11:54:04.876044 (MainThread): Completed successfully
2021-08-05 11:54:04.876167 (MainThread): 
Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
2021-08-05 11:54:04.876379 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ac7c9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10abf5fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10abf58b0>]}
2021-08-05 11:54:04.876576 (MainThread): Flushing usage events
2021-08-05 11:54:42.431533 (MainThread): Running with dbt=0.20.0
2021-08-05 11:54:42.729044 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=False, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=False, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/Users/daniel/.dbt', profile=None, target=None, vars='{}', log_cache_events=False, use_cache=True, threads=None, models=None, exclude=None, selector_name=None, state=None, defer=None, cls=<class 'dbt.task.snapshot.SnapshotTask'>, which='snapshot', rpc_method='snapshot')
2021-08-05 11:54:42.730230 (MainThread): Tracking: tracking
2021-08-05 11:54:42.742279 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ec5abe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ecac460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ecac400>]}
2021-08-05 11:54:42.781716 (MainThread): Partial parsing not enabled
2021-08-05 11:54:42.825369 (MainThread): Parsing macros/metric_approx_distinct_count.sql
2021-08-05 11:54:42.827247 (MainThread): Parsing macros/metric_sum.sql
2021-08-05 11:54:42.828560 (MainThread): Parsing macros/metric_count.sql
2021-08-05 11:54:42.829475 (MainThread): Parsing macros/metric_max.sql
2021-08-05 11:54:42.830798 (MainThread): Parsing macros/metric_count_distinct.sql
2021-08-05 11:54:42.832720 (MainThread): Parsing macros/metric_avg.sql
2021-08-05 11:54:42.834289 (MainThread): Parsing macros/metric_min.sql
2021-08-05 11:54:42.835734 (MainThread): Parsing macros/anonymise/extract_email_domain.sql
2021-08-05 11:54:42.836112 (MainThread): Parsing macros/generate/generate_enrich_model.sql
2021-08-05 11:54:42.838855 (MainThread): Parsing macros/etc.sql
2021-08-05 11:54:42.840475 (MainThread): Parsing macros/catalog.sql
2021-08-05 11:54:42.846333 (MainThread): Parsing macros/adapters.sql
2021-08-05 11:54:42.862930 (MainThread): Parsing macros/materializations/seed.sql
2021-08-05 11:54:42.865171 (MainThread): Parsing macros/materializations/view.sql
2021-08-05 11:54:42.867476 (MainThread): Parsing macros/materializations/table.sql
2021-08-05 11:54:42.875913 (MainThread): Parsing macros/materializations/copy.sql
2021-08-05 11:54:42.879622 (MainThread): Parsing macros/materializations/incremental.sql
2021-08-05 11:54:42.890332 (MainThread): Parsing macros/materializations/snapshot.sql
2021-08-05 11:54:42.891784 (MainThread): Parsing macros/core.sql
2021-08-05 11:54:42.895084 (MainThread): Parsing macros/materializations/test.sql
2021-08-05 11:54:42.900989 (MainThread): Parsing macros/materializations/helpers.sql
2021-08-05 11:54:42.910114 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-08-05 11:54:42.911540 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-08-05 11:54:42.927398 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-08-05 11:54:42.961482 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-08-05 11:54:42.980495 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-08-05 11:54:42.981974 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-08-05 11:54:42.988611 (MainThread): Parsing macros/materializations/common/merge.sql
2021-08-05 11:54:43.001409 (MainThread): Parsing macros/materializations/table/table.sql
2021-08-05 11:54:43.007572 (MainThread): Parsing macros/materializations/view/view.sql
2021-08-05 11:54:43.013208 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-08-05 11:54:43.017258 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-08-05 11:54:43.017963 (MainThread): Parsing macros/etc/query.sql
2021-08-05 11:54:43.018746 (MainThread): Parsing macros/etc/is_incremental.sql
2021-08-05 11:54:43.020113 (MainThread): Parsing macros/etc/datetime.sql
2021-08-05 11:54:43.027663 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-08-05 11:54:43.029295 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-08-05 11:54:43.030587 (MainThread): Parsing macros/adapters/common.sql
2021-08-05 11:54:43.074042 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-08-05 11:54:43.075836 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-08-05 11:54:43.076809 (MainThread): Parsing macros/schema_tests/unique.sql
2021-08-05 11:54:43.077933 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-08-05 11:54:43.079884 (MainThread): Parsing macros/cross_db_utils/except.sql
2021-08-05 11:54:43.080770 (MainThread): Parsing macros/cross_db_utils/replace.sql
2021-08-05 11:54:43.081826 (MainThread): Parsing macros/cross_db_utils/concat.sql
2021-08-05 11:54:43.082665 (MainThread): Parsing macros/cross_db_utils/datatypes.sql
2021-08-05 11:54:43.087923 (MainThread): Parsing macros/cross_db_utils/_is_relation.sql
2021-08-05 11:54:43.088901 (MainThread): Parsing macros/cross_db_utils/length.sql
2021-08-05 11:54:43.090002 (MainThread): Parsing macros/cross_db_utils/dateadd.sql
2021-08-05 11:54:43.092494 (MainThread): Parsing macros/cross_db_utils/intersect.sql
2021-08-05 11:54:43.093400 (MainThread): Parsing macros/cross_db_utils/right.sql
2021-08-05 11:54:43.095531 (MainThread): Parsing macros/cross_db_utils/datediff.sql
2021-08-05 11:54:43.104852 (MainThread): Parsing macros/cross_db_utils/safe_cast.sql
2021-08-05 11:54:43.106481 (MainThread): Parsing macros/cross_db_utils/hash.sql
2021-08-05 11:54:43.107715 (MainThread): Parsing macros/cross_db_utils/cast_bool_to_text.sql
2021-08-05 11:54:43.108935 (MainThread): Parsing macros/cross_db_utils/identifier.sql
2021-08-05 11:54:43.110383 (MainThread): Parsing macros/cross_db_utils/position.sql
2021-08-05 11:54:43.111839 (MainThread): Parsing macros/cross_db_utils/literal.sql
2021-08-05 11:54:43.112627 (MainThread): Parsing macros/cross_db_utils/current_timestamp.sql
2021-08-05 11:54:43.115638 (MainThread): Parsing macros/cross_db_utils/width_bucket.sql
2021-08-05 11:54:43.120340 (MainThread): Parsing macros/cross_db_utils/last_day.sql
2021-08-05 11:54:43.123566 (MainThread): Parsing macros/cross_db_utils/split_part.sql
2021-08-05 11:54:43.125134 (MainThread): Parsing macros/cross_db_utils/date_trunc.sql
2021-08-05 11:54:43.126400 (MainThread): Parsing macros/cross_db_utils/_is_ephemeral.sql
2021-08-05 11:54:43.128172 (MainThread): Parsing macros/materializations/insert_by_period_materialization.sql
2021-08-05 11:54:43.152058 (MainThread): Parsing macros/web/get_url_host.sql
2021-08-05 11:54:43.153619 (MainThread): Parsing macros/web/get_url_path.sql
2021-08-05 11:54:43.156284 (MainThread): Parsing macros/web/get_url_parameter.sql
2021-08-05 11:54:43.157638 (MainThread): Parsing macros/jinja_helpers/pretty_log_format.sql
2021-08-05 11:54:43.158578 (MainThread): Parsing macros/jinja_helpers/pretty_time.sql
2021-08-05 11:54:43.159680 (MainThread): Parsing macros/jinja_helpers/log_info.sql
2021-08-05 11:54:43.160664 (MainThread): Parsing macros/jinja_helpers/slugify.sql
2021-08-05 11:54:43.161666 (MainThread): Parsing macros/schema_tests/fewer_rows_than.sql
2021-08-05 11:54:43.163141 (MainThread): Parsing macros/schema_tests/equal_rowcount.sql
2021-08-05 11:54:43.164543 (MainThread): Parsing macros/schema_tests/relationships_where.sql
2021-08-05 11:54:43.166553 (MainThread): Parsing macros/schema_tests/recency.sql
2021-08-05 11:54:43.168127 (MainThread): Parsing macros/schema_tests/not_constant.sql
2021-08-05 11:54:43.169247 (MainThread): Parsing macros/schema_tests/accepted_range.sql
2021-08-05 11:54:43.171455 (MainThread): Parsing macros/schema_tests/not_accepted_values.sql
2021-08-05 11:54:43.173302 (MainThread): Parsing macros/schema_tests/test_unique_where.sql
2021-08-05 11:54:43.174527 (MainThread): Parsing macros/schema_tests/at_least_one.sql
2021-08-05 11:54:43.175674 (MainThread): Parsing macros/schema_tests/unique_combination_of_columns.sql
2021-08-05 11:54:43.178251 (MainThread): Parsing macros/schema_tests/cardinality_equality.sql
2021-08-05 11:54:43.179987 (MainThread): Parsing macros/schema_tests/expression_is_true.sql
2021-08-05 11:54:43.181537 (MainThread): Parsing macros/schema_tests/sequential_values.sql
2021-08-05 11:54:43.183949 (MainThread): Parsing macros/schema_tests/test_not_null_where.sql
2021-08-05 11:54:43.185244 (MainThread): Parsing macros/schema_tests/equality.sql
2021-08-05 11:54:43.188308 (MainThread): Parsing macros/schema_tests/mutually_exclusive_ranges.sql
2021-08-05 11:54:43.196465 (MainThread): Parsing macros/sql/date_spine.sql
2021-08-05 11:54:43.200596 (MainThread): Parsing macros/sql/nullcheck_table.sql
2021-08-05 11:54:43.201976 (MainThread): Parsing macros/sql/get_relations_by_pattern.sql
2021-08-05 11:54:43.204955 (MainThread): Parsing macros/sql/generate_series.sql
2021-08-05 11:54:43.209224 (MainThread): Parsing macros/sql/get_relations_by_prefix.sql
2021-08-05 11:54:43.212391 (MainThread): Parsing macros/sql/get_tables_by_prefix_sql.sql
2021-08-05 11:54:43.213857 (MainThread): Parsing macros/sql/star.sql
2021-08-05 11:54:43.216816 (MainThread): Parsing macros/sql/unpivot.sql
2021-08-05 11:54:43.224197 (MainThread): Parsing macros/sql/union.sql
2021-08-05 11:54:43.232268 (MainThread): Parsing macros/sql/groupby.sql
2021-08-05 11:54:43.233899 (MainThread): Parsing macros/sql/surrogate_key.sql
2021-08-05 11:54:43.237701 (MainThread): Parsing macros/sql/safe_add.sql
2021-08-05 11:54:43.239254 (MainThread): Parsing macros/sql/nullcheck.sql
2021-08-05 11:54:43.240698 (MainThread): Parsing macros/sql/get_tables_by_pattern_sql.sql
2021-08-05 11:54:43.246905 (MainThread): Parsing macros/sql/get_column_values.sql
2021-08-05 11:54:43.251474 (MainThread): Parsing macros/sql/pivot.sql
2021-08-05 11:54:43.255125 (MainThread): Parsing macros/sql/get_query_results_as_dict.sql
2021-08-05 11:54:43.257174 (MainThread): Parsing macros/sql/haversine_distance.sql
2021-08-05 11:54:43.262501 (MainThread): Parsing macros/generate_model_yaml.sql
2021-08-05 11:54:43.265320 (MainThread): Parsing macros/generate_source_yaml.sql
2021-08-05 11:54:43.271457 (MainThread): Parsing macros/generate_base_model.sql
2021-08-05 11:54:43.274040 (MainThread): Parsing macros/get_date_dimension.sql
2021-08-05 11:54:43.297411 (MainThread): Parsing macros/get_base_dates.sql
2021-08-05 11:54:43.302183 (MainThread): Parsing macros/fiscal_date/get_fiscal_year_dates.sql
2021-08-05 11:54:43.306217 (MainThread): Parsing macros/fiscal_date/get_fiscal_periods.sql
2021-08-05 11:54:43.307876 (MainThread): Parsing macros/calendar_date/tomorrow.sql
2021-08-05 11:54:43.308413 (MainThread): Parsing macros/calendar_date/next_week.sql
2021-08-05 11:54:43.308878 (MainThread): Parsing macros/calendar_date/next_month_name.sql
2021-08-05 11:54:43.309482 (MainThread): Parsing macros/calendar_date/next_month.sql
2021-08-05 11:54:43.309972 (MainThread): Parsing macros/calendar_date/day_name.sql
2021-08-05 11:54:43.312980 (MainThread): Parsing macros/calendar_date/to_unixtimestamp.sql
2021-08-05 11:54:43.314539 (MainThread): Parsing macros/calendar_date/n_days_away.sql
2021-08-05 11:54:43.315160 (MainThread): Parsing macros/calendar_date/week_start.sql
2021-08-05 11:54:43.317963 (MainThread): Parsing macros/calendar_date/iso_week_start.sql
2021-08-05 11:54:43.320276 (MainThread): Parsing macros/calendar_date/n_days_ago.sql
2021-08-05 11:54:43.321210 (MainThread): Parsing macros/calendar_date/last_week.sql
2021-08-05 11:54:43.321687 (MainThread): Parsing macros/calendar_date/now.sql
2021-08-05 11:54:43.322203 (MainThread): Parsing macros/calendar_date/periods_since.sql
2021-08-05 11:54:43.322838 (MainThread): Parsing macros/calendar_date/today.sql
2021-08-05 11:54:43.323304 (MainThread): Parsing macros/calendar_date/last_month.sql
2021-08-05 11:54:43.323779 (MainThread): Parsing macros/calendar_date/day_of_year.sql
2021-08-05 11:54:43.325496 (MainThread): Parsing macros/calendar_date/last_month_start_date.sql
2021-08-05 11:54:43.325974 (MainThread): Parsing macros/calendar_date/from_unixtimestamp.sql
2021-08-05 11:54:43.331294 (MainThread): Parsing macros/calendar_date/n_months_ago.sql
2021-08-05 11:54:43.332141 (MainThread): Parsing macros/calendar_date/date_part.sql
2021-08-05 11:54:43.333391 (MainThread): Parsing macros/calendar_date/n_weeks_away.sql
2021-08-05 11:54:43.334198 (MainThread): Parsing macros/calendar_date/day_of_month.sql
2021-08-05 11:54:43.335121 (MainThread): Parsing macros/calendar_date/yesterday.sql
2021-08-05 11:54:43.335665 (MainThread): Parsing macros/calendar_date/day_of_week.sql
2021-08-05 11:54:43.342542 (MainThread): Parsing macros/calendar_date/iso_week_end.sql
2021-08-05 11:54:43.344571 (MainThread): Parsing macros/calendar_date/next_month_start_date.sql
2021-08-05 11:54:43.345047 (MainThread): Parsing macros/calendar_date/n_weeks_ago.sql
2021-08-05 11:54:43.345986 (MainThread): Parsing macros/calendar_date/month_name.sql
2021-08-05 11:54:43.348673 (MainThread): Parsing macros/calendar_date/last_month_name.sql
2021-08-05 11:54:43.349286 (MainThread): Parsing macros/calendar_date/week_of_year.sql
2021-08-05 11:54:43.350926 (MainThread): Parsing macros/calendar_date/convert_timezone.sql
2021-08-05 11:54:43.355055 (MainThread): Parsing macros/calendar_date/n_months_away.sql
2021-08-05 11:54:43.355857 (MainThread): Parsing macros/calendar_date/next_week_start_date.sql
2021-08-05 11:54:43.356329 (MainThread): Parsing macros/calendar_date/this_week.sql
2021-08-05 11:54:43.356836 (MainThread): Parsing macros/calendar_date/iso_week_of_year.sql
2021-08-05 11:54:43.359600 (MainThread): Parsing macros/calendar_date/week_end.sql
2021-08-05 11:54:43.361759 (MainThread): Parsing macros/calendar_date/next_month_number.sql
2021-08-05 11:54:43.362328 (MainThread): Parsing macros/calendar_date/last_month_number.sql
2021-08-05 11:54:43.362893 (MainThread): Parsing macros/utils/datatypes.sql
2021-08-05 11:54:43.364194 (MainThread): Parsing macros/regex/regexp_instr.sql
2021-08-05 11:54:43.366272 (MainThread): Parsing macros/math/log_natural.sql
2021-08-05 11:54:43.367724 (MainThread): Parsing macros/math/rand.sql
2021-08-05 11:54:43.369237 (MainThread): Parsing macros/math/median.sql
2021-08-05 11:54:43.369720 (MainThread): Parsing macros/math/percentile_cont.sql
2021-08-05 11:54:43.371528 (MainThread): Parsing macros/schema_tests/_generalized/expression_between.sql
2021-08-05 11:54:43.375229 (MainThread): Parsing macros/schema_tests/_generalized/expression_is_true.sql
2021-08-05 11:54:43.378888 (MainThread): Parsing macros/schema_tests/_generalized/equal_expression.sql
2021-08-05 11:54:43.392909 (MainThread): Parsing macros/schema_tests/_generalized/_truth_expression.sql
2021-08-05 11:54:43.393718 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_like_pattern.sql
2021-08-05 11:54:43.394828 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_like_pattern_list.sql
2021-08-05 11:54:43.396854 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_regex.sql
2021-08-05 11:54:43.398082 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_value_lengths_to_equal.sql
2021-08-05 11:54:43.399191 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_value_lengths_to_be_between.sql
2021-08-05 11:54:43.400781 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_regex.sql
2021-08-05 11:54:43.402032 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_regex_list.sql
2021-08-05 11:54:43.404001 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_match_regex_list.sql
2021-08-05 11:54:43.405972 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_like_pattern_list.sql
2021-08-05 11:54:43.407998 (MainThread): Parsing macros/schema_tests/string_matching/_get_like_pattern_expression.sql
2021-08-05 11:54:43.408609 (MainThread): Parsing macros/schema_tests/string_matching/expect_column_values_to_not_match_like_pattern.sql
2021-08-05 11:54:43.409726 (MainThread): Parsing macros/schema_tests/table_shape/expect_row_values_to_have_recent_data.sql
2021-08-05 11:54:43.410647 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_columns_to_contain_set.sql
2021-08-05 11:54:43.411921 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table.sql
2021-08-05 11:54:43.412815 (MainThread): Parsing macros/schema_tests/table_shape/expect_grouped_row_values_to_have_recent_data.sql
2021-08-05 11:54:43.415290 (MainThread): Parsing macros/schema_tests/table_shape/expect_column_to_exist.sql
2021-08-05 11:54:43.417530 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_equal.sql
2021-08-05 11:54:43.419938 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_be_between.sql
2021-08-05 11:54:43.421335 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_row_count_to_equal_other_table_times_factor.sql
2021-08-05 11:54:43.422057 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_columns_to_match_set.sql
2021-08-05 11:54:43.423392 (MainThread): Parsing macros/schema_tests/table_shape/_get_column_list.sql
2021-08-05 11:54:43.424256 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_columns_to_match_ordered_list.sql
2021-08-05 11:54:43.425819 (MainThread): Parsing macros/schema_tests/table_shape/_list_intersect.sql
2021-08-05 11:54:43.426733 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_column_count_to_equal_other_table.sql
2021-08-05 11:54:43.427753 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_column_count_to_equal.sql
2021-08-05 11:54:43.428558 (MainThread): Parsing macros/schema_tests/table_shape/expect_table_column_count_to_be_between.sql
2021-08-05 11:54:43.430504 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_not_be_in_set.sql
2021-08-05 11:54:43.432129 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql
2021-08-05 11:54:43.433798 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_increasing.sql
2021-08-05 11:54:43.435262 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_null.sql
2021-08-05 11:54:43.436244 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_unique.sql
2021-08-05 11:54:43.436837 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_between.sql
2021-08-05 11:54:43.438302 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_decreasing.sql
2021-08-05 11:54:43.439777 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_in_type_list.sql
2021-08-05 11:54:43.442512 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_be_of_type.sql
2021-08-05 11:54:43.443060 (MainThread): Parsing macros/schema_tests/column_values_basic/expect_column_values_to_not_be_null.sql
2021-08-05 11:54:43.443995 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_min_to_be_between.sql
2021-08-05 11:54:43.445545 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_unique_value_count_to_be_between.sql
2021-08-05 11:54:43.447096 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_quantile_values_to_be_between.sql
2021-08-05 11:54:43.448758 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_median_to_be_between.sql
2021-08-05 11:54:43.450341 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_proportion_of_unique_values_to_be_between.sql
2021-08-05 11:54:43.451994 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_equal_set.sql
2021-08-05 11:54:43.453739 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_most_common_value_to_be_in_set.sql
2021-08-05 11:54:43.458202 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_contain_set.sql
2021-08-05 11:54:43.459951 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal.sql
2021-08-05 11:54:43.461245 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_sum_to_be_between.sql
2021-08-05 11:54:43.462757 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_stdev_to_be_between.sql
2021-08-05 11:54:43.465933 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_mean_to_be_between.sql
2021-08-05 11:54:43.467456 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_max_to_be_between.sql
2021-08-05 11:54:43.468962 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_be_greater_than.sql
2021-08-05 11:54:43.470244 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql
2021-08-05 11:54:43.472090 (MainThread): Parsing macros/schema_tests/aggregate_functions/expect_column_distinct_count_to_equal_other_table.sql
2021-08-05 11:54:43.473646 (MainThread): Parsing macros/schema_tests/distributional/expect_row_values_to_have_data_for_every_n_datepart.sql
2021-08-05 11:54:43.479508 (MainThread): Parsing macros/schema_tests/distributional/expect_column_values_to_be_within_n_moving_stdevs.sql
2021-08-05 11:54:43.488782 (MainThread): Parsing macros/schema_tests/distributional/expect_column_values_to_be_within_n_stdevs.sql
2021-08-05 11:54:43.492021 (MainThread): Parsing macros/schema_tests/multi-column/expect_select_column_values_to_be_unique_within_record.sql
2021-08-05 11:54:43.498617 (MainThread): Parsing macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql
2021-08-05 11:54:43.503763 (MainThread): Parsing macros/schema_tests/multi-column/expect_multicolumn_sum_to_equal.sql
2021-08-05 11:54:43.505871 (MainThread): Parsing macros/schema_tests/multi-column/expect_column_pair_values_to_be_equal.sql
2021-08-05 11:54:43.507164 (MainThread): Parsing macros/schema_tests/multi-column/expect_column_pair_values_A_to_be_greater_than_B.sql
2021-08-05 11:54:43.508532 (MainThread): Parsing macros/schema_tests/multi-column/expect_column_pair_values_to_be_in_set.sql
2021-08-05 11:54:43.976397 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders".
2021-08-05 11:54:44.024152 (MainThread): Acquiring new bigquery connection "model.dbt_shop.iowa_liquor_sales".
2021-08-05 11:54:44.028767 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer_payments__base_js".
2021-08-05 11:54:44.033254 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__base_js".
2021-08-05 11:54:44.037694 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__base_js".
2021-08-05 11:54:44.041951 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__base_abc".
2021-08-05 11:54:44.045934 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer_payments__base_abc".
2021-08-05 11:54:44.050597 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__base_abc".
2021-08-05 11:54:44.054276 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__agg".
2021-08-05 11:54:44.065817 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__enrich".
2021-08-05 11:54:44.080898 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__enrich".
2021-08-05 11:54:44.084242 (MainThread): Acquiring new bigquery connection "model.dbt_shop.sales_orders__blend".
2021-08-05 11:54:44.088765 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer__blend".
2021-08-05 11:54:44.093304 (MainThread): Acquiring new bigquery connection "model.dbt_shop.customer_payments__blend".
2021-08-05 11:54:44.105848 (MainThread): Acquiring new bigquery connection "snapshot.dbt_shop.orders_snapshot".
2021-08-05 11:54:44.111639 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ee20070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ec78730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ec78070>]}
2021-08-05 11:54:44.111815 (MainThread): Flushing usage events
2021-08-05 11:54:45.303433 (MainThread): Connection 'snapshot.dbt_shop.orders_snapshot' was properly closed.
2021-08-05 11:54:45.303650 (MainThread): Encountered an error:
2021-08-05 11:54:45.303850 (MainThread): Compilation Error in snapshot orders_snapshot (snapshots/orders.sql)
  at path []: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.
2021-08-05 11:54:45.312060 (MainThread): Traceback (most recent call last):
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 361, in render_update
    self.update_parsed_node(node, config)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 304, in update_parsed_node
    config_dict = config.build_config_dict()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/context/context_config.py", line 274, in build_config_dict
    return src.calculate_node_config_dict(
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/context/context_config.py", line 202, in calculate_node_config_dict
    finalized = config.finalize_and_validate()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/contracts/graph/model_config.py", line 498, in finalize_and_validate
    self.validate(data)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/contracts/graph/model_config.py", line 471, in validate
    raise ValidationError(
hologram.ValidationError: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 406, in run
    self._runtime_initialize()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 122, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 79, in _runtime_initialize
    self.load_manifest()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 66, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 170, in get_full_manifest
    manifest = loader.load()
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 254, in load
    self.parse_project(
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 363, in parse_project
    parser.parse_file(block)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/snapshots.py", line 80, in parse_file
    self.parse_node(block)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 385, in parse_node
    self.render_update(node, config)
  File "/Users/daniel/git/dbrtly/dbt_shop/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 365, in render_update
    raise CompilationException(msg, node=node) from exc
dbt.exceptions.CompilationException: Compilation Error in snapshot orders_snapshot (snapshots/orders.sql)
  at path []: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.

### PR DESCRIPTION
**Pull request by dbrtly**
resolves #3694 

### Description

Normally for BigQuery connection profiles, dataset is a synonym for schema to reflect the BigQuery jargon but there was a bug for snapshots with this synonym.

Comments with conjunctions (eg. isn't, wasn't, aren't) do not play nicely with linting in vscode and were hard to read to used the slightly more verbose expressions for clearer syntax highlighting where I noticed it but avoided hunting for it across the entire repo.

### Checklist

- [X ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [X ] This PR includes tests, or tests are not required/relevant for this PR
- [X ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

NB: 
As discussed I could not get the integration tests to run locally
I may have edited the change log incorrectly.

### CODE REVIEW

**Comment by dbrtly** [comment]
I signed this again just now

**Comment by dbrtly** [comment]
Signed a third time with the other email address. Maybe that was the problem.

**Comment by jtcohen6** [comment]
@cla-bot check

File: test/integration/004_simple_snapshot_test/test-check-col-snapshots-bq/snapshot.sql [hunk 1]
```diff
@@ -1,10 +1,10 @@
 {% snapshot snapshot_actual %}
     {# this used to be check_cols=('email',), which ought to be totally valid,
-    but isn't because type systems are hard. #}
+    but is not because type systems are hard. #}
     {{
         config(
             target_database=var('target_database', database),
-            target_schema=schema,
+            target_schema=var('target_schema', schema),
```
Comment (jtcohen6) [inline test/integration/004_simple_snapshot_test/test-check-col-snapshots-bq/snapshot.sql:7]: To test that the aliasing works, could you provide the actual config names as `target_project` (instead of `target_database`) and `target_dataset` (instead of `target_schema`)?

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 ## dbt 0.21.0 (Release TBD)
 
+### Fixes
+
+- Fix bigquery-specific synonym for schema (dataset) for snapshots. ([#3694](https://github.com/dbt-labs/dbt/issues/3694), [#xxxx](https://github.com/dbt-labs/dbt/pull/xxxx tba))
```
Comment (jtcohen6) [inline CHANGELOG.md:5]: It looks like there's a merge conflict with the changelog file, which happens when we've merged other PRs in the meantime. Could you pull the latest changes from `develop`, and then also add yourself to the list of Contributors? :)

**Review by jtcohen6 — COMMENTED** [review]
Thanks for the contribution @dbrtly! The change itself looks good to me. I left two quick comments that should be straightforward to address.

File: CHANGELOG.md (hunk 2 above)
Comment (dbrtly) [reply CHANGELOG.md]: * fixed merge conflict from upstream.
* added PR ref number in changelog
* added myself to contributors
* set integration test config to use the alias 
Thanks Jeremy

File: test/integration/004_simple_snapshot_test/test-check-col-snapshots-bq/snapshot.sql (hunk 1 above)
Comment (dbrtly) [reply test/integration/004_simple_snapshot_test/test-check-col-snapshots-bq/snapshot.sql]: edited config to use alias as described

**Review by jtcohen6 — APPROVED** [review]
Thanks for the contribution @dbrtly!

I just updated the changelog to resolve a merge conflict. As soon as the last round of tests pass, I'll merge this in for v0.21 :)
